

export const apiDomain = import.meta.env.VITE_API_BASE_URL
export const ApiConfig = {
  Account: {
    GetAllRoles: "Account/GetAllRoles",
    GetAdminRoles: apiDomain + "Account/GetAllRoles/false",
    LogOut: "Account/Logout",
    ValidateUserLogin: "Account/ValidateUserLogIn",
    GetRoleResources: apiDomain + "Account/GetAllRolePermissions",
    GetPermissions: apiDomain + "Account/GetAllPermissions",
    CreateRoleResources: apiDomain + "Account/CreateRolePermission",
    UpdateRoleResources: apiDomain + "Account/UpdateRolePermission",
  },
  Users: {
    ValidateUserFirstTimeLogIn: "Account/ValidateUserFirstTimeLogIn",
    CreateAccount: "Account/Register",
    GetAllIndustries: "Account/GetAllIndustries",
    GetAllCategories: "Account/GetAllCategories",
    ValidateSettlementAccount: apiDomain + "Account/ValidateSettlementAccount",
  },
  Merchants: {
    Profile: "Merchants/ProfileMerchant",
    Update: "Merchants/UpdateMerchant",
    MerchantByID: "Merchants/GetMerchantById/",
    UploadKYCDocument: "Merchants/UploadKYCDocuments",
    PendingKYCDocuments:
      apiDomain + "Merchants/GetAllMerchantKYCsPendingApproval",
    RejectedKYCDocuments: apiDomain + "Merchants/GetAllRejectedMerchantKYCs",
    AllKYCDocuments: apiDomain + "Merchants/GetAllMerchantKYCs",
    ApprovedKYCDocuments: apiDomain + "Merchants/GetAllApprovedMerchantKYCs",
    ApproveMerchantKYC: apiDomain + "Merchants/ApproveMerchantKyc",
    GetFileById: apiDomain + "Merchants/GetFileById",
    GetMerchantUsers: apiDomain + "Users/GetUsersByMerchantId/",
    GetSSOUsers: apiDomain + "Users/GetInternalUsers",
    CreateMerchantUsers: apiDomain + "Users/CreateMerchantUser",
    UpdateMerchantUsers: apiDomain + "Users/UpdateUser",
    GetMerchantRoles: apiDomain + "Account/GetAllRoles/true",
    GetMerchantKYC: apiDomain + "Merchants/KycDocumentStatus/",
    ReUploadFile: apiDomain + "Merchants/Re-uploadKyc",
    RegisterWebhook: apiDomain + "WebhookRegistration/RegisterWebhook",
    GetNotification: apiDomain + "Merchants/GetNotification/",
    UpdateNotification: apiDomain + "Merchants/UpdateNotification",
    ValidateReceipt: apiDomain + "Payments/ValidateReceipt/",
  },
  Approvals: {
    GetAllMerchantChargePendingApproval:
      apiDomain + "Approvals/GetAllMerchantChargePendingApproval",
    ApproveMerchantCharge: apiDomain + "Approvals/ApproveMerchantCharge",
    DisapproveMerchantCharge: apiDomain + "Approvals/DisapproveMerchantCharge",
  },
  SetUp: {
    GetAllBanks: "PGSetup/GetAllBanks",
    TransactionLimit: apiDomain + "PGSetup/GetAllTransactionLimit",
    GetAllProviders: apiDomain + "PGSetup/GetAllProviders",
    GetBanks: apiDomain + "PGSetup/GetAllBanks",
    CreateProvider: apiDomain + "PGSetup/CreateProvider",
    UpdateProvider: apiDomain + "PGSetup/UpdateProvider",
    GetAllBin: apiDomain + "PGSetup/GetAllBins",
    CreateBin: apiDomain + "PGSetup/CreateBin",
    UpdateBin: apiDomain + "PGSetup/UpdateBin",
    GetAllBrands: apiDomain + "PGSetup/GetAllCardBrands",
    ManageCardTransaction: apiDomain + "PGSetup/ManageCardTransaction",
    GetAllMerchant: apiDomain + "PGSetup/GetAllMerchants",
    UpdateMerchant: apiDomain + "Merchants/UpdateRegCompletedMerchant",
    MapMerchant: apiDomain + "Merchants/FetchOldMerchantIdFromV2",
    UpdateBanks: apiDomain + "PGSetup/UpdateBank",
    GetTransactionLimit: apiDomain + "PGSetup/GetAllTransactionLimit",
    UpdateTransactionLimit: apiDomain + "PGSetup/UpdateTransactionLimit",
    CreateTransactionLimit: apiDomain + "PGSetup/CreateTransactionLimit",
  },
  Report: {
    GetAdminTranReport: apiDomain + "Report/GetTransactionReportForAdmin",
    GetMerchantTranReport: apiDomain + "Report/GetTransactionReportForMerchant",
    GetAdditionalReport: apiDomain + "Report/GetTransactionReportForFountain"
  },
  PaymentPage: {
    GetMerchantPages: apiDomain + "PaymentPages/GetAllPages/",
    AddPage: apiDomain + "PaymentPages/Add",
    Update: apiDomain + "PaymentPages/Update",
    ValidateLink: apiDomain + "PaymentPages/ValidatePaymentPageLinkRefernce/",
    GetTransactions: apiDomain + "PaymentPages/GetPaymentPageTransactions/",
  },
  Product: {
    Create: apiDomain + "Product/CreateProduct",
    Update: apiDomain + "Product/UpdateProduct",
    Duplicate: apiDomain + "Product/DuplicateProduct/",
    Delete: apiDomain + "Product/DeleteProduct/",
    Upload: apiDomain + "Product/UploadProductImages",
    GetProduct: apiDomain + "Product/GetProducts/",
    ValidateProductLink: apiDomain + "Product/ValidateProductReference/",
    GetProductTransation: apiDomain + "Product/GetProductTransaction/",
  },
  Store: {
    GetStore: apiDomain + "Store/GetStores/",
    AddStore: apiDomain + "Store/CreateStore",
    UpdateStore: apiDomain + "Store/UpdateStore",
    ValidateLink: apiDomain + "Store/ValidateStoreLink/",
    GetStoreByID: apiDomain + "Store/GetStoreByID/",
    DeleteStore: apiDomain + "Store/DeleteStore/",
    GetProductNotInStore: apiDomain + "Store/GetProductsNotInStore?merchantId=",
    GetStoreTransaction: apiDomain + "Store/GetStoreTransactions/",
  },
};

export default ApiConfig;
