export const endpoints = {
  GetAppStatistics: "mock/statistics.json",
  GetUsers: "mock/user.json",
  GetTopTen: "mock/topten.json",
  Account: {
    GetAllRoles: "Accounts/GetAllRoles",
    GetAdminRoles: "Accounts/GetAllRoles/false",
    LogOut: "Accounts/Logout",
    ValidateUserLogin: "Accounts/ValidateUserLogIn",
    GetRoleResources: "Accounts/GetAllRolePermissions",
    GetPermissions: "Accounts/GetAllPermissions",
    CreateRoleResources: "Accounts/CreateRolePermission",
    UpdateRoleResources: "Accounts/UpdateRolePermission",
    GetSubAccountGroup: "Accounts/GetMerchantSubAccountGroup?",
    GetSubAccount: "Accounts/GetMerchantSubAccount?",
  },
  Users: {
    ValidateUserFirstTimeLogIn: "Admin/ValidateUserFirstTimeLogIn",
    GetAllIndustries: "Accounts/GetAllIndustries",
    GetAllCategories: "Accounts/GetAllCategories",
    ValidateSettlementAccount: "Merchants/ValidateSettlementAccount",
    GetInternalUsers: "Admin/GetInternalUsers",
    UpdateUser: "Admin/UpdateUsers",
  },
  Approvals: {
    GetAllMerchantChargePendingApproval:
      "Approvals/GetAllMerchantChargePendingApproval",
    ApproveMerchantCharge: "Approvals/ApproveMerchantCharge",
    DisapproveMerchantCharge: "Approvals/DisapproveMerchantCharge",
  },
  SetUp: {
    GetAllBanks: "Setup/GetAllBanks",
    TransactionLimit: "Setup/GetAllTransactionLimit",
    GetAllProviders: "Setup/GetAllProviders",
    GetBanks: "Setup/GetAllBanks",
    CreateProvider: "Setup/CreateProvider",
    UpdateProvider: "Setup/UpdateProvider",
    GetAllBin: "Setup/GetAllBins",
    CreateBin: "Setup/CreateBin",
    UpdateBin: "Setup/UpdateBin",
    GetAllBrands: "Setup/GetAllCardBrands",
    ManageCardTransaction: "Setup/ManageCardTransaction",
    GetAllMerchant: "Setup/GetAllMerchants",
    UpdateMerchant: "Admin/UpdateRegCompletedMerchant",
    MapMerchant: "Merchants/FetchOldMerchantIdFromV2",
    UpdateBanks: "Setup/UpdateBank",
    GetTransactionLimit: "Setup/GetAllTransactionLimit",
    UpdateTransactionLimit: "Setup/UpdateTransactionLimit",
    CreateTransactionLimit: "Setup/CreateTransactionLimit",
    GetAllPaymentMethod: "SetUp/GetAllPaymentMethod",
    UpdatePaymentMethod: "SetUp/UpsertPaymentMethod",
    GetAllStorePaymentMethods: "SetUp/GetAllStorePaymentMethods",
    UpdateStorePaymentMethod: "SetUp/UpdateStorePaymentMethod",
    GetMerchantPaymentMethod: "SetUp/GetMerchantPaymentMethod/",
    UpdateMerchantPaymentMethod: "SetUp/UpdatePaymentMethod/"
  },
  Report: {
    GetAdminTranReport: "Report/GetTransactionReportForAdmin",
    GetMerchantTranReport: "Report/GetTransactionReportForMerchant",
    GetAdditionalReport: "Report/GetTransactionReportForFountain",
    Download: "api/Report/Downloads",
    DownloadForFountain: "api/Report/DownloadFountain",
    GetAuditReport: "/Admin/GetAuditLogs",
    DownloadSplit: "SplitPayment/Downloads",
  },
  PaymentPage: {
    GetMerchantPages: "PaymentPages/GetAllPages/",
    AddPage: "PaymentPages/Add",
    Update: "PaymentPages/Update",
    ValidateLink: "PaymentPages/ValidatePaymentPageLinkRefernce/",
    GetTransactions: "PaymentPages/GetPaymentPageTransactions/",
  },
  QR: {
    CreateMerchant: "NIBSS/CreateMerchant",
    GetQrMerchant: "NIBSS/GetQrMerchant",
    GetQrSubMerchant: "NIBSS/GetQrSubMerchant",
    UpdateQrSubMerchant: "NIBSS/UpdateQrSubMerchant",
    UpdateQrMerchant: "NIBSS/UpdateQrMerchant",
    BindMerchantAccount: "NIBSS/BindMerchantAccount",
    CreateSubMerchant: "NIBSS/CreateSubMerchant",
  },
};
