export {default as lanndingImage} from "./landing-img.png"
export {default as logo} from "./logo.png"
export {default as NgnFlag} from "./NgnFlag.svg"
export {default as logoImg} from "./logo.png"
export {default as LogoutIcon} from "./logout.png"