export const ROUTE_PATH = {
  Landing: "/",
  GetStarted: "/get-started",
  Dashboard: "/dashboard",
  Merchant: "/merchant",
  Roles: "/roles",
  QrMerchant: "/nqr/merchant",
  QrSubMerchant: "/nqr/sub-merchant",
  Users: "/users",
  Profile: "/profile",
  MerchantApproval: "/approval/merchant",
  Transaction: "/payment/transaction",
  Split: "/payment/split",
  Store: "/payment/store",
  SubAccount: "/payments/sub-account",
  SubAccountGroup: "payments/sub-account-groups",
  Provider: "/setup/provider",
  Bin: "/setup/bin",
  Institution: "setup/institution",
  TransactionManager: "setup/transaction-manager",
  AuditTrail: "/audit-trail",
  Login: import.meta.env.VITE_AUTH_DOMAIN,
  UnAuthorize: "/403",
};

export enum KycStatus {
  APPROVED = "APPROVED",
  PENDING = "PENDING",
  DECLINED = "DECLINED",
}
export enum AppStorageKeys {
  Token = "*****",
  UserInfo = "***",
  MerchantPortalToken = "**",
}
export enum APIResponseCode {
  Success = "00",
  BadRequest = "ERR_BAD_REQUEST",
  RedirectToXpressPay = "05",
  Invalid = "04",
  Pending = "06",
  Failed = "02",
}

export enum AppPermissions {
  CreateUser = "Create User",
  UpdateUser = "Update User",
  ViewUser = "View User",
  ViewAllUsers = "View All Users",
  CreateRole = "Create Role",
  UpdateRole = "Update Role",
  ViewRole = "View Role",
  ViewAllRoles = "View All Roles",
  ViewResources = "View Resources",
  ViewRolesResources = "View Roles Resources",
  UpdateMerchant = "Update Merchant",
  ViewMerchant = "View Merchant",
  ViewAllMerchants = "View All Merchants",
  ViewKYCDocument = "View KYC Document",
  ApproveKYC = "Approve KYC",
  CreateProvider = "Create Provider",
  UpdateProvider = "Update Provider",
  ViewProvider = "View Provider",
  ViewAllProvider = "View All Provider",
  CreateBin = "Create Bin",
  UpdateBin = "Update Bin",
  ViewBin = "View Bin",
  ViewAllBin = "View All Bin",
  ViewCardTransactionManager = "View Card Transaction Manager",
  UpdateCardTransactionManager = "Update Card Transaction Manager",
  ViewAllCardTransactionManager = "View All Card Transaction Manager",
  CreateInstitutions = "Create Institutions",
  UpdateInstitutions = "Update Institutions",
  ViewInstitutions = "View Institutions",
  ViewAllInstitutions = "View All Institutions",
  ViewTransactionDetailsMenu = "View Transaction Details Menu",
  ViewTransactionsReport = "View Transactions Report",
  DownloadFile = "Download File",
  ViewMerchantApproval = " View Merchant Approval ",
  ApproveMerchantChargeSetup = "Approve Merchant Charge Setup",
  ViewMerchantKYC = "View Merchant KYC",
  ViewMerchantKey = "View Merchant Key",
  DownloadMerchantTransaction = "Download Merchant Transaction",
  ValidateReceipt = "Validate Receipt",
}
