export namespace APIRequest {
    export interface MerchantRequest {
        id: number
        userId: string
        businessName: string
        businessType: string
        businessNumber: string
        staffSize: string
        industry: string
        serviceCategory: string
        businessEmail: string
        supportEmail: string
        disputeEmail: string
        businessAddress: string
        settlementAccountNumber: string
        accountName: string
        bankCode: string
        isActive: boolean
        cardPayment: boolean
        accountPayment: boolean
        ussdPayment: boolean
        qrPayment: boolean
        walletPayment: boolean
        bankTrasferPayment: boolean
        businessLogo: string
        transactionLimit: number
        dateProfiled: string
        dateUpdated: string
        website: string
        twitterAccount: string
        facebookAccount: string
        instagramAccount: string
        isRegistrationCompleted: boolean
        productDescription: string
        merchantCategory: string
        kycStatus: string
        updatedBy: string
        webHookUrl: string
        useBin: boolean
        useStaticRoute: boolean
        staticRouteProvider: string
        useDefault: boolean
        defaultProvider: string
        categoryName: string
        directorName: string
        bvn: string
        registrationStatus: string
        chargeType: string
        firstName: string
        lastName: string
        chargeValue: string
        chargeCap: number
        isKycApproved: boolean
        isChargeTransferedToCustomer: boolean
        comments: string
        approvalStatus: number
        disapprovedComment: string
        isPaymentPageCustomizationEnabled: boolean
        directIntegrationStatus: number
        oldMerchantId: string
        oldGatewayMerchantId: string
        isKeysVisible: boolean
        disabled: boolean
        tokenization: boolean
        eNaira: boolean
        receiveInternationalPayment: boolean
        merchantPortalId: string
      }
      
}